name: build-extension
on:
  release:
    types:
    - created

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        npm ---version
        npm ci
    - name: Run build
      run: |-
        npm run package -- -o mudly-formatter.vsix
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: mudly-formatter.vsix
        asset_name: mudly-formatter.vsix
        asset_content_type: application/octet-stream
