name: build-mudly
on:
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-latest
          name: linux
        - os: macos-latest
          name: darwin
        arch:
        - GOARCH: "386"
          label: x86
        - GOARCH: amd64
          label: amd64
        exclude:
        - platform:
            os: macos-latest
            name: darwin
          arch:
            GOARCH: "386"
            label: x86
    name: Build & Publish
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies
      run: |
        go version
        go get ./cmd/mudly
    - name: Run build
      run: GOARCH=${{ matrix.arch.GOARCH }} go build -o=bin/mudly-${{ matrix.platform.name }}-${{ matrix.arch.label }} -v ./cmd/mudly
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: bin/mudly-${{ matrix.platform.name }}-${{ matrix.arch.label }}
        asset_name: mudly-${{ matrix.platform.name }}-${{ matrix.arch.label }}
        asset_content_type: application/octet-stream
