name: build-mudly
on:
  release:
    types:
    - created
    - edited

jobs:
  build:
    name: Build Go [${{ matrix.platform }}]
    runs-on: ubuntu-latest
    env: 
      ARTIFACT_NAME: mudly-1.16-${{ matrix.platform }}-x64
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, darwin, win32]
    steps:
    - uses: actions/checkout@v2

    - name: Build Go 1.16
      run: |
        ./builders/build-go.ps1 -Platform ${{ matrix.platform }}
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ runner.temp }}/artifact