name: build-mudly
on:
  release:
    types:
    - created

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies
      run: |
        go version
        go get ./cmd/mudly
    - name: Run build
      run: go build -o=bin/mudly -v ./cmd/mudly
    - name: Upload Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: bin/mudly
        asset_name: mudly
        asset_content_type: application/octet-stream
